# Generated by Django 4.1.3 on 2022-11-11 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=600)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('tag', models.CharField(choices=[('BOOK', 'Book Review'), ('ARTICLE', 'Article'), ('SOFTWARE', 'Software'), ('GAMING', 'Gaming'), ('LANGUAGE', 'Language'), ('FICTION', 'Fiction')], default='ARTICLE', max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('userID', models.TextField(default='Anonymous')),
                ('body', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_application.article')),
            ],
        ),
    ]
